import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = {
  title: "Hands-On AI Classes and Training in Dallas, TX",
  description: "Beginner-friendly ChatGPT classes, private AI tutoring, community education, and business AI workshops serving Dallas and the DFW Metroplex.",
  alternates: { canonical: "/dallas-ai-training" },
  openGraph: { title: "Hands-On AI Training in Dallas–Fort Worth", description: "Practical, human-guided AI classes for beginners, creators, seniors, community groups, and businesses in DFW.", url: "/dallas-ai-training", type: "website" },
};

const areas = ["Dallas", "Oak Cliff", "Cockrell Hill", "Cedar Hill", "DeSoto", "Duncanville", "Lancaster", "Grand Prairie", "Irving", "Arlington", "Fort Worth"];
const schema = { "@context":"https://schema.org", "@type":"ProfessionalService", name:"AI Clarity Sessions", url:"https://aiclaritysessions.com/dallas-ai-training", email:siteConfig.supportEmail, description:"Hands-on artificial intelligence education and training serving the Dallas–Fort Worth Metroplex.", founder:{"@type":"Person",name:"Osborn G. Nelson II"}, areaServed:areas.map((name)=>({"@type":"City",name})), serviceType:["AI classes","ChatGPT training","Private AI tutoring","Corporate AI workshops","Community AI education"] };

export default function DallasAiTrainingPage() {
  return <main id="main-content" className="local-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} /><section className="local-hero"><div className="site-container"><p className="eyebrow">Dallas–Fort Worth AI education</p><h1>Practical AI training,<br />built for real people.</h1><p>Osborn G. Nelson II provides patient, hands-on AI and ChatGPT education for beginners, creators, seniors, families, businesses, and community organizations across DFW.</p><div><Link className="button-primary" href="/#pricing">View upcoming classes</Link><Link className="button-secondary" href="/contact">Discuss private training</Link></div></div></section><section className="local-content site-container"><div><h2>Learning that starts where you are</h2><p>These are guided working sessions, not technical lectures. Learners practice asking stronger questions, creating useful content, checking accuracy, protecting private information, and building simple workflows they can use after class.</p><h2>Flexible formats for Dallas-area learners</h2><div className="local-cards"><article><h3>Public beginner classes</h3><p>Structured small-group sessions with published dates and live seat availability.</p></article><article><h3>Private AI tutoring</h3><p>One-on-one guidance shaped around your device, goals, pace, and everyday questions.</p></article><article><h3>Business and team workshops</h3><p>Practical training focused on responsible adoption, useful workflows, and shared standards.</p></article><article><h3>Community education</h3><p>Accessible sessions for churches, nonprofits, senior groups, families, and neighborhood organizations.</p></article></div></div><aside><h2>Service area</h2><p>Sessions are arranged online or at an agreed venue. There is no advertised walk-in storefront.</p><ul>{areas.map((area)=><li key={area}>{area}</li>)}</ul><p>Other Dallas–Fort Worth locations may be available by arrangement.</p></aside></section><section className="local-cta"><h2>Bring your questions.<br />Leave with a clear next step.</h2><Link className="button-primary" href="/#pricing">Find a class</Link></section></main>;
}
